company:
  name: 株式会社富士越
  business_name: サービス・ブランド名を入力してください
  industry: 業界を入力してください（例：美容業界、IT業界、飲食業界）
  location: '（例: 東京都新宿区）'
  prefecture: 東京都
  city: 中野区
  key_features:
  - 主要な特徴や強みを3-5個記載してください
  - 例：24時間対応、業界最安値、資格保有者在籍
  - 例：口コミ評価◯◯No.1、創業◯◯年の実績
  services:
    primary_service: 主要サービス名
    price_range: 価格帯（例：○○円〜、月額○○円）
    special_offers: 特別なプランやキャンペーン
  contact:
    phone: 電話番号
    email: メールアドレス
    website: https://fujikoshi.net/
    hours: 営業時間（例：24時間、9:00-18:00）
industry:
  name: 業界名
  market_size: 市場規模（例：○○億円市場）
  growth_rate: 成長率（例：年率○％成長）
  characteristics:
  - 業界の特徴を3-5個記載してください
  - 例：必需品サービス、競争が激しい、季節性あり
  customer_behavior:
  - 顧客の行動パターンを記載してください
  - 例：価格重視、口コミ重視、緊急性高い
  challenges:
  - 業界の主要な課題を記載してください
  - 例：人手不足、デジタル化の遅れ、価格競争
competitors:
  target_companies:
  - name: 競合企業名A
    website: https://example.com
    category: 大手チェーン/地域密着/オンライン/その他
  - name: 競合企業名B
    website: https://example.com
    category: 大手チェーン/地域密着/オンライン/その他
  - name: 競合企業名C
    website: https://example.com
    category: 大手チェーン/地域密着/オンライン/その他
  analysis_points:
  - 価格競争力
  - サービス品質
  - デジタル対応力
  - 地域カバレッジ
  - 顧客満足度
seo:
  primary_keywords:
  - メインキーワード1（例：サービス名 + 地域）
  - メインキーワード2（例：業界名 + 地域）
  - メインキーワード3（例：課題 + 解決）
  secondary_keywords:
  - サブキーワード1
  - サブキーワード2
  - サブキーワード3
  local_keywords:
  - 地域特化キーワード1
  - 地域特化キーワード2
  informational:
  - ○○とは
  - ○○の選び方
  - ○○の相場
  navigational:
  - 企業名
  - 企業名 + 評判
  - 企業名 + 口コミ
  transactional:
  - ○○ 申し込み
  - ○○ 予約
  - ○○ 相談
target_customers:
  primary:
    name: プライマリーペルソナ名
    age: 年齢層（例：30-50代）
    situation: 置かれている状況
    needs: 主要なニーズ
    search_behavior: 検索行動パターン
  secondary:
    name: セカンダリーペルソナ名
    age: 年齢層
    situation: 置かれている状況
    needs: 主要なニーズ
    search_behavior: 検索行動パターン
  notes: '（例: 年齢層/状況/ニーズ/検索行動のヒント）'
marketing_goals:
  primary_goal: 主要な目標（例：問い合わせ数増加、売上向上）
  target_metrics:
  - 目標指標1（例：月間問い合わせ数○○件）
  - 目標指標2（例：成約率○○％）
  - 目標指標3（例：リピート率○○％）
  timeline: 達成期間（例：3ヶ月、6ヶ月）
  budget: 予算（例：月額○○万円）
landing_page:
  purpose: LPの目的（例：問い合わせ獲得、資料請求）
  target_action: ターゲットアクション（例：電話、フォーム送信）
  design_preference: '（例: シンプル/高級感/親しみやすさ/ミニマル など）'
  key_sections:
  - メインビジュアル
  - サービス紹介
  - お客様の声
  - 料金・プラン
  - 会社紹介
  - お問い合わせ
quality_control:
  required_completion_rate: 95
  mandatory_reviews:
  - 競合分析の妥当性
  - SEOキーワードの適切性
  - ターゲット設定の具体性
  - LP要件の実装可能性
  success_criteria:
  - 全TODOマーカーの更新完了
  - 競合優位性の明確化
  - 実装可能なLP要件定義
  - 測定可能なKPI設定
